---
title: "Data Wrangling"
format: html
---


Windows: Ctrl + Alt + I
```{r}
#|message: false
library(dplyr)
library(tidyr)
library(readr)
```
stats::filter()
dplyr::filter()
##Reading in the Data

```{r}
catch_original<- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

#Explaining the Data

```{r}
#prints column names
colnames(catch_original)

#reads first 6 lines of data
#head(catch_original)

#unique values in each column
unique(catch_original$Region)

#summary of each column
summary(catch_original)
```
## Clean and Reshaping
%>%  Ctr Shift M

%>% = and then

### Using Select() Function

```{r}
catch_data<-catch_original %>% 
  select(Region,Year,Chinook,Sockeye,Pink,Chum)
head(catch_data)
```

```{r}
catch_data <- catch_original %>% 
  select(-All,-notesRegCode)
dplyr::glimpse(catch_data)
```
##Change column content using mutate()

```{r}
catch_clean<- catch_data %>% 
  #change the column type to numeric, left column name you want, and then middle is function you want, 
  mutate(Chinook= as.numeric(Chinook))

head(catch_clean)
```
```{r}
i <- which(is.na(catch_clean$Chinook))
i
```
```{r}
catch_data[i,]
```

```{r}
#If the Chinook column value is I then change it to 1 if true and false keep the same. And also change Chinook cloumn to numeric
catch_clean <- catch_data%>%
  mutate(Chinook= dplyr::if_else(condition= Chinook== "I", true= "1", false= Chinook), Chinook=as.numeric(Chinook))
catch_clean[i,]
```
### Changing shape of data frame

```{r}
catch_long<- catch_clean%>%
  #pivot longer except for region and year
  pivot_longer(cols = -c(Region, Year),names_to="Species",values_to= "catch")
head(catch_long)
```

```{r}
catch_wide<- catch_long %>%
  pivot_wider(names_from = Species,values_from = catch)

head(catch_wide)
```
#Renaming a column
```{r}
catch_long<- catch_long %>% rename(catch_thousands=catch)

head(catch_long)
```

##Adding columns
```{r}
catch_long<- catch_long %>%
mutate(catch= catch_thousands *1000) %>% 
select(-catch_thousands)
head(catch_long)
```
#Summary Statistics
```{r}
unique(catch_original$Region)

```
```{r}
#Summarize will calculate mean catch for each region
mean_region<-catch_long %>% group_by(Region) %>% summarize(mean_catch=mean(catch))
head(mean_region)
```
###Filtering Rows using filter()



